### ISSUE TITLE
Create MaterialMappings.xml relative to creating script

### ISSUE THREAD

**Issue by cpetry** [Pjbomb2/TrueTrace-Unity-Pathtracer#10]
In my project I place every plugin/third party asset in assemblies and another subfolder. (i.e.: ...Assets\Plugins\TrueTrace)
Due to this the MaterialMappings.xml can't be found/created by your solution here.

Can you please create the file relative to the script that creates the file?

**Comment by Pjbomb2** [comment]
Hmmmmm thats...strange
I always thought it would be included with the download... so theres no script that actually creates it... I will change that now!

**Comment by Pjbomb2** [comment]
Ok, I made it so that the XML file will be created on start if it is missing, lemme know if its still broken!

**Comment by Pjbomb2** [comment]
wait I commpletely fucked up the tracing

**Comment by Pjbomb2** [comment]
Fixed now

**Comment by cpetry** [comment]
I used "Application.temporaryCachePath" here to quickly fix this.
I didn't see where the file is referenced from other scripts, so I guess you would need to adjust on other locations too.
File will get created if it does not exist

**Comment by Pjbomb2** [comment]
Had to get rid of the backup creation of the xml file unfortunately as in URP or HDRP it could get a race conflict and break the xml with half a new header pasted ontop of the old one
