### ISSUE TITLE
Some meshes not visible

### ISSUE THREAD

**Issue by cpetry** [Pjbomb2/TrueTrace-Unity-Pathtracer#12]
Hello,

I managed to get it to work on my fully dynamic project.
All my meshes/models get created in runtime and it somehow works.

Some of the meshes though were not shown at first.
After playing around with the settings a bit I enabled/disabled "Enable Object Moving" and now I also see these models.
Even if it's disabled now. Perhaps some cache that got created? unsure...

**Comment by Pjbomb2** [comment]
You need to have "Enable Objects Moving" on in order for objects to spawn/despawn/move
