### ISSUE TITLE
Update "Ray Tracing Object" on material change

### ISSUE THREAD

**Issue by cpetry** [Pjbomb2/TrueTrace-Unity-Pathtracer#13]
Hello,

in my project I can freely change materials of all dynamic objects.
How can I update the "Ray Tracing Object" to re-evaluate or recreate the information there to the actual new material set?

**Comment by cpetry** [comment]
I figured it out:

- Click "Build Aggregated BVH"
- enable + disable "EnableObjectMoving" to update something it seems...

Could this update be done automatically ofter "Build Aggregated BVH" please?

**Comment by Pjbomb2** [comment]
What do you mean? It should instantly update as long as enable obejct moving is on?

**Comment by Pjbomb2** [comment]
I think I only just understood what this meant fully... the reason why I havent done this so far is that that would require checking all properties of a material every frame, will look to see if theres a callback I can use tho

**Comment by Pjbomb2** [comment]
I have added callable functions that allow you to tell truetrace when a material has changed, as its not performance friendly to check everything automatically unfortunately
