### ISSUE TITLE
Some emissive materials not shown correctly

### ISSUE THREAD

**Issue by cpetry** [Pjbomb2/TrueTrace-Unity-Pathtracer#14]
I have some emissive materials that are not shown correctly.
It seems that the RayTracingObject BaseColor needs to be set manually
On my emissive materials the baseColor is black and only the emissive color is set:
![image](https://user-images.githubusercontent.com/3867700/233561924-a1b563a4-587e-4d8b-a14f-31160b063659.png)

Seems that the value then not gets applied correctly:
![image](https://user-images.githubusercontent.com/3867700/233562042-b0b37604-2faa-408e-8542-dbf6a0b005e5.png)

**Comment by Pjbomb2** [comment]
On first creation/if told to link, RayTracingObjects will inherit the properties of their associated material with respect to the links defined in the material linking xml, but it will only happen when the object is built
