### ISSUE TITLE
Take MaterialPropertyBlock into account

### ISSUE THREAD

**Issue by cpetry** [Pjbomb2/TrueTrace-Unity-Pathtracer#15]
I'm heavily using MaterialPropertyBlocks to adjust minor changes on materials.
See this here:
https://docs.unity3d.com/ScriptReference/MaterialPropertyBlock.html

![image](https://user-images.githubusercontent.com/3867700/233563061-89094ef8-6871-491b-9d5d-b1366e357992.png)

When rendering with your TrueTrace these settings seem not to be taken into account:
![image](https://user-images.githubusercontent.com/3867700/233563191-8030b28f-c16b-44e1-b96b-9a9f3fcd9b19.png)

In this case here I changed the UV scaling of the texture

**Comment by Pjbomb2** [comment]
Added a callable function that allows you to tell it when you change the scale/offset of a texture, as checking this automatically could be a major performance drain with many objects
