### ISSUE TITLE
Execute before PostProcess Stack

### ISSUE THREAD

**Issue by iamtanmay** [Pjbomb2/TrueTrace-Unity-Pathtracer#18]
Hi Pjbomb2 testing the Pathtracer, I tried to stack it with PostProcess and it seems to be applied after the PostProcessing. Would it be possible to render it before PostProcess ?

There is an FSR 2.0 PostProcess which gives significant frame rate improvements by upscaling. I use it in most of my projects and it would probably be quite useful to make the Pathtracer even more performant.

**Comment by Pjbomb2** [comment]
Which render pipeline? and yeah I have tried with the github unity fsr 2.2, and its pretty good but janky(not a fault of it, more a fault with unity restrictions)

**Comment by iamtanmay** [comment]
Hi Pjbomb2. I tried with BuiltIn.

I got decent results with FSR set to Quality with SSRT GI effects. 

An example demo: https://file.io/sDJx2gnsL0T1

Toggle between NoFSR and different quality levels by pressing 0

**Comment by Pjbomb2** [comment]
mhm! It works, but I want to do more testing with it first
