### ISSUE TITLE
URP and HDRP compability, mipmap

### ISSUE THREAD

**Issue by tugrulsubekci** [Pjbomb2/TrueTrace-Unity-Pathtracer#21]
- I tried working with unity version 2022.3.4f1 with URP. Path tracing just didn't start 
- I tried working with unity version 2023.2.8f1 with HDRP. At the start, I have a black screen and huge performance problem

There is no error in the console for both of them. Tried on DemoScene which came with package. Also all materials converted with unity's asset converter. I looked all the documenation but I couldn't found any solution.

And do you use mipmap? Don't using mipmaps, cause a weird view on textures. I attached a file for this.

![2024-02-05 14-16-02, 0 Samples](https://github.com/Pjbomb2/TrueTrace-Unity-Pathtracer/assets/104980354/bdc934cb-c8c9-4bba-8414-71128b82bc63)

**Comment by Pjbomb2** [comment]
URP, did you add the URPcompatability script to the renderer or whatever? I forget what it exactly is
HDRP, did you add HDRPCompatability to a custom pass?

**Comment by Pjbomb2** [comment]
Also for the albedo texture I do not use mipmaps rn
